sudo: required

env:
  global:
    - IMAGE="dprotsenko/fluentd"
    - COMMIT=${TRAVIS_COMMIT::7}

services:
  - docker

before_script:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $COMMIT ; fi`
  - docker build -t $IMAGE:$COMMIT .
  - docker tag $IMAGE:$COMMIT $IMAGE:$TAG
  - docker push $IMAGE
