sudo: required

services:
  - docker

before_script:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

script:
  - docker build -t .

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $COMMIT ; fi`
